### ISSUE TITLE
ResultPoints can sometimes be null

### ISSUE THREAD

**Issue by Kamuno** [SecUSo/privacy-friendly-qr-scanner#68] opened 2020-03-03 23:59 UTC
Reported on Sony Xperia 5 (J9210), 5632MB RAM, Android 10

`java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3276)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3415)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:83)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2022)
  at android.os.Handler.dispatchMessage (Handler.java:107)
  at android.os.Looper.loop (Looper.java:359)
  at android.app.ActivityThread.main (ActivityThread.java:7418)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:492)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:935)
Caused by: java.lang.NullPointerException: 
  at com.journeyapps.barcodescanner.SourceData.translateResultPoint (SourceData.java:103)
  at com.journeyapps.barcodescanner.BarcodeResult.transformResultPoints (BarcodeResult.java:172)
  at com.journeyapps.barcodescanner.BarcodeResult.getTransformedResultPoints (BarcodeResult.java:68)
  at com.journeyapps.barcodescanner.BarcodeResult.getBitmapWithResultPoints (BarcodeResult.java:78)
  at com.secuso.privacyfriendlycodescanner.qrscanner.ui.viewmodel.ResultViewModel.initFromScan (ResultViewModel.java:67)
  at com.secuso.privacyfriendlycodescanner.qrscanner.ui.activities.ResultActivity.initStateIfNecessary (ResultActivity.java:111)
  at com.secuso.privacyfriendlycodescanner.qrscanner.ui.activities.ResultActivity.onCreate (ResultActivity.java:81)
  at android.app.Activity.performCreate (Activity.java:7802)
  at android.app.Activity.performCreate (Activity.java:7791)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1307)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3251)`

**Comment by derEisbaerX** [comment] 2020-10-09 20:09
Hi Kamuno
I couldn't reproduce this error. The case "ResultPoints=null" is handeled in com.journeyapps.barcodescanner.BarcodeResult.
Do you have an idea or additional information? I think we can close this issue otherwise because it's pretty old.

**Comment by Kamuno** [comment] 2020-10-11 08:56
![image](https://user-images.githubusercontent.com/11301924/95674397-3ff36f00-0bb0-11eb-90b0-699b8c6a3fa0.png)
This issue is not as important.. there are more severe ones. It occured 17 times in the lifetime of the app.

**Closed** 2022-06-24 11:25 UTC
Labels: bug
